import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
    useEffect(() => {
        if (window) {
            try {
                setTimeout(() => {
                    const iframe = window.frames["myFrame"].contentWindow;
                    console.log(iframe);
                    const iframeDoc = iframe.document;
                    const ele = iframeDoc.getElementById("bookContainer");
                    const newEle = ele.cloneNode(true);
                    ele.parentNode.replaceChild(newEle, ele);
                    console.log(iframeDoc, ele);
                    if (ele) {
                        ele.onscroll = () => {};
                    }
                }, [3000]);
            } catch (error) {
                console.log(error);
            }
        }
    }, []);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <iframe
                id="myFrame"
                src="/iframe"
                width="900px"
                height="600px"
            ></iframe>
        </div>
    );
}
