import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import ChildComp from "../components/ChildComp";
import styles from "../styles/Home.module.css";

export default function Home() {

    const [isMounted, setIsMounted] = useState(false);
    useEffect(()=>{
//         const vw = Math.max((document.documentElement.clientWidth || 0), window.innerWidth || 0)
// const vh = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0)
        setIsMounted(true);
    },[])
    
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {isMounted && <ChildComp/>}

            <div style={{padding: "50px"}}>
            {[...Array(10000).keys()].map(item => {
                return (
                    <div key={item} className={styles.item}>
                        lorem {item}
                    </div>
                )
            })}
            </div>
        </div>
    );
}
